//
//  REQUESTURL.h
//  E展会
//
//  Created by 徐仁强 on 15/8/22.
//  Copyright (c) 2015年 徐仁强. All rights reserved.
//

#ifndef E___REQUESTURL_h
#define E___REQUESTURL_h

#define REQUESTURL @"http://web.ronghaohuishou.cn/rule_user_service.jsp"
#define ESHOWNO2URL @"http://os.ehuizhan.com.cn/app/"
#define MAPAPIKEY @"38750fa975ad70f76c6981a1da8f693d"
#define MORENTOUXAING @"MORENTOUXIANG"
#define MORENMAN @"男"
#define MORENWOMAN @"Ů"
#define MORENQIYE @"企业"
#define MORENTUPIAN @"我-背景"
#define MORENSHANGJIA @"3.jpg"
#define INDEXURL ESHOWNO2URL"index!exhibitionIndex.action";
#define HOTZHANHUI ESHOWNO2URL"index!hotExhibition.action"
#define XINPIN ESHOWNO2URL"index!newProduct.action"
#define ZHANZHOU ESHOWNO2URL"index!exhibitionList.action"
#define GUANZHUXINPIN ESHOWNO2URL"exhibition!onProFollow.action"
#define ZHANHUIYE ESHOWNO2URL"exhibition!exDetail.action"
#define RUZHU ESHOWNO2URL"exhibition!enterSave.action"
#define YUYUECHULI ESHOWNO2URL"exhibition!refuseOrApprove.action"
#define GUANZHUZHANHUI ESHOWNO2URL"exhibition!onFollow.action"
#define HUICHANGSAOMA ESHOWNO2URL"exhibition!exScan.action"
#define GUANZHUZHANSHANG ESHOWNO2URL"user_app!onFollow.action"
#define JUBAOLAHEI ESHOWNO2URL"user_app!report.action"
#define ZHANHUIFUWU ESHOWNO2URL"exhibition!serviceList.action"
#define ZHANHUIFUWULEIXING ESHOWNO2URL"exhibition!serviceTypeList.action"
#define NEWSCENTER ESHOWNO2URL"exhibition!newsList.action"
#define NEWSDETAILS ESHOWNO2URL"exhibition!newsDetail.action"
#define LUNTANLIST ESHOWNO2URL"exhibition!forumList.action"
#define LUNTANDETAIL ESHOWNO2URL"exhibition!forumDetail.action"
#define ZHANSHANGLIEBIAO ESHOWNO2URL"exhibition!exBusinessList.action"
#define EXBUSINESSLIST ESHOWNO2URL"exhibition!exBusinessList.action"
#define ZHANSHANGXIANGQING ESHOWNO2URL"exhibition!exBusinessDetail.action"
#define ZHANWEILIST ESHOWNO2URL"exhibition!exPosition.action"
#define ZHANHUIXINPIN ESHOWNO2URL"exhibition!newProduct.action"
#define QIANDAO ESHOWNO2URL"user_app!userSign.action"
#define QIANDAOLIST ESHOWNO2URL"user_app!userSignList.action"
#define CHANPINXIANGQING ESHOWNO2URL"exhibition!productDetail.action"
#define RUZHUYUYUELIST ESHOWNO2URL"exhibition!enterList.action"
#define XINPINXIANGQING ESHOWNO2URL"exhibition!productDetail.action"
#define ZHAOHUANLISHI ESHOWNO2URL"reshis!gethis.action"
#define ZHAOHUANDETAIL ESHOWNO2URL"reshis!getDetail.action"
#define SENDZHAOHUAN ESHOWNO2URL"reshis!addCall.action"
#define ZHAOHUANHANGYE ESHOWNO2URL"reshis!getInd.action"
#define ZHAOHUANRECI ESHOWNO2URL"reshis!getHotword.action"
#define ZHAOHUANLI ESHOWNO2URL"reshis!getWordhis.action"
#define ZHAOHUANXIANGYING ESHOWNO2URL"reshis!searchres.action"
#define ISJIESHOUZHAOHUAN ESHOWNO2URL"reshis!control.action"
#define FAXIANFUWU ESHOWNO2URL"find!exServe.action"
#define FAXIANMINGQI ESHOWNO2URL"find!famousEnterprise.action"
#define FAXIANMINGXING ESHOWNO2URL"find!famousOrganize.action"
#define FAXIANXINPIN ESHOWNO2URL"find!newProduct.action"
#define FAXIANLIUYANBAN ESHOWNO2URL"find!findguestbook.action"
#define FAXIANFUJIN ESHOWNO2URL"find!nearby.action"
#define FABULIUYAN ESHOWNO2URL"find!saveGuest.action"
#define SENDVIDEO ESHOWNO2URL"find!createGuest.action"
#define LIUYANXIANGQING ESHOWNO2URL"find!guestDetail.action"
#define LIUYANDELE ESHOWNO2URL"find!deleteGuest.action"
#define SHENQINGXX ESHOWNO2URL"user_app!userQuaApply.action"
#define SHENQINGXINPINTUIJIAN ESHOWNO2URL"user_app!recommendApply.action"
#define DELEPRODICT ESHOWNO2URL"exhibition!deleteProduct.action"
#define DELEPRODICTIMAGE ESHOWNO2URL"exhibition!delProImg.action"
#define ZSBZSET ESHOWNO2URL"actor!zsbzSet.action"
#define DELETEEXBUSI ESHOWNO2URL"exhibition!deleteExBusi.action"
#define ASSOLIST ESHOWNO2URL"asso!assoList.action"
#define ASSODETAIL ESHOWNO2URL"asso!assoDetail.action"
#define INFOLIST ESHOWNO2URL"asso!infoList.action"
#define INFODETAIL ESHOWNO2URL"asso!infoDetail.action"
#define MEMBLISTURL ESHOWNO2URL"asso!membList.action"
#define MEMBHISTORYURL ESHOWNO2URL"asso!membHistory.action"
#define MEMBINFOLISTURL ESHOWNO2URL"asso!membInforsList.action"
#define MEETINGLIST ESHOWNO2URL"meeting_app!meetingList.action"
#define MEETINGDETAIL ESHOWNO2URL"meeting_app!meetingDetail.action"
#define MEETINGTONGZHILIST ESHOWNO2URL"meeting_app!newsList.action"
#define MEETINGTONGZHIDETAIL ESHOWNO2URL"meeting_app!newsDetail.action"
#define MEETINGRICHENGLIST ESHOWNO2URL"meeting_app!forumList.action"
#define MEETINGRICHENGDETAIL ESHOWNO2URL"meeting_app!forumDetail.action"
#define MEETINGSIGN ESHOWNO2URL"meeting_app!signSave.action"
#define MEETINGSIGNLIST ESHOWNO2URL"meeting_app!signList.action"
#define MEETINGENTERSAVE ESHOWNO2URL"meeting_app!enterSave.action"
#define MEETINGENTERSAVELIST ESHOWNO2URL"meeting_app!enterList.action"
#define MEETINGENTERADD ESHOWNO2URL"meeting_app!enterAdd.action"
#define BAOMINGCHANGE ESHOWNO2URL"meeting_app!enterSave.action"
#define APPLYCASHTOALIPAY ESHOWNO2URL"balance!applyCashToAlipay.action"
#define NEWADDINFOLIST ESHOWNO2URL"infomation_app!infoList.action"
#define NEWADDINFODETAIL ESHOWNO2URL"infomation_app!infoDetail.action"
#define ZHANHUILIUYANBANLIEBIAO ESHOWNO2URL"find!guestbookList.action"
#define UPLOADFILERICHTEXTURL  ESHOWNO2URL"product_app!uploadFiles.action"




#endif
